import React from 'react';

function Summary({ pages }) {
  return (
    <div className="bg-white p-8 rounded-2xl shadow-lg border border-gray-200 max-w-4xl mx-auto">
      <h2 className="text-2xl md:text-3xl font-bold mb-6 text-blue-600 border-b border-gray-200 pb-3 text-center">
        📄 Document Summary
      </h2>

      <div className="space-y-6">
        {pages.map((page, index) => (
          <div
            key={index}
            className="bg-gray-50 p-5 rounded-xl border border-gray-100 hover:shadow-md transition duration-300"
          >
            <h3 className="text-lg font-semibold text-blue-500 mb-2">
              Page {page.page}
            </h3>
            <p className="text-gray-700 whitespace-pre-wrap leading-relaxed">
              {page.summary}
            </p>
          </div>
        ))}
      </div>

      <p className="text-center text-sm text-gray-500 mt-8">
        📘 Generated by Global AI Knowledge Bridge
      </p>
    </div>
  );
}

export default Summary;
